// <auto-generated />
namespace Employees.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Newtablerelationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Newtablerelationships));
        
        string IMigrationMetadata.Id
        {
            get { return "201802261641175_New table relationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
