// <auto-generated />
namespace Employees.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UploadTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UploadTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201801301609250_Upload Test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
